# Generated by Django 5.2.9 on 2025-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_item_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dono da Loja'), ('STAFF', 'Funcionário')], default='STAFF', max_length=10),
        ),
    ]
