# Generated by Django 5.2.9 on 2026-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(default='00000000000', help_text='Apenas números com DDD (ex:11999998888)', max_length=20),
            preserve_default=False,
        ),
    ]
