# Generated by Django 5.2.9 on 2026-03-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_restaurant_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/covers/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/'),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dono da Loja'), ('STAFF', 'Funcionário'), ('CLIENT', 'Cliente')], default='STAFF', max_length=10),
        ),
    ]
