# Generated by Django 5.2.9 on 2026-03-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_restaurant_cover_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cover',
            new_name='banner',
        ),
    ]
