# Generated by Django 5.2.9 on 2026-03-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_rename_cover_restaurant_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/banner/'),
        ),
    ]
