# Generated by Django 5.2.9 on 2026-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_restaurant_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
