# Generated by Django 5.2.9 on 2026-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_restaurant_is_active_partnerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Em dia'), ('pending', 'Pendente'), ('late', 'Atrasado'), ('blocked', 'Bloqueado')], default='pending', max_length=20),
        ),
    ]
