# Generated by Django 5.2.9 on 2026-04-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_restaurant_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.restaurant'),
        ),
    ]
