# Generated by Django 5.2.9 on 2026-04-19 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_alter_storeprofile_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.restaurant'),
            preserve_default=False,
        ),
    ]
